build.gradle
src/main/java/com/bunq/sdk/context/ApiContext.java
src/main/java/com/bunq/sdk/model/generated/Card.java
src/main/java/com/bunq/sdk/security/MacOutputStream.java
src/main/java/com/bunq/sdk/security/SecurityUtils.java

Fix Jitpack build, add misssing fields, fix field types in generated [#6]

---

.gitignore
src/main/java/com/bunq/sdk/context/ApiContext.java
src/test/java/com/bunq/sdk/context/ApiConfigTest.java
src/test/java/com/bunq/sdk/context/ApiContextTest.java

add methods to save ApiContext to JSON and restore it from JSON [#9]

---

.gitignore
src/main/java/com/bunq/sdk/context/ApiContext.java
src/main/java/com/bunq/sdk/http/ApiClient.java

Add proxy support and missing .gitignore entry [#11]

---

.gitattributes

Added git attributes.

---

src/main/java/com/bunq/sdk/context/ApiContext.java
src/main/java/com/bunq/sdk/http/ApiClient.java

#23 
This pr introduces a new way to handle `SessionContext`. Now it is possible to do the following:
```
if (apiContext.isExpired()) {
apiContext.resetSession();
apiContext.save();
}
```
This way there is no saving an unchanged context.
Closes #23

Added isExpired() method #23.

---

src/main/java/com/bunq/sdk/model/generated/endpoint/Card.java
src/main/java/com/bunq/sdk/model/generated/endpoint/CardDebit.java
src/main/java/com/bunq/sdk/model/generated/endpoint/CardGeneratedCvc2.java
src/main/java/com/bunq/sdk/model/generated/endpoint/CashRegister.java
src/main/java/com/bunq/sdk/model/generated/endpoint/MonetaryAccountBank.java
src/main/java/com/bunq/sdk/model/generated/endpoint/UserCompany.java
src/main/java/com/bunq/sdk/model/generated/endpoint/UserPerson.java

#26 
https://doc.bunq.com/api/1/call/card-generated-cvc2 has been added in the SDK

Added cvc_endpoint. #26

---

.github/ISSUE_TEMPLATE.md
src/main/java/com/bunq/sdk/model/generated/endpoint/CardGeneratedCvc2.java

This pr adds an issue template as well for speeding up the creation of new issues.
Fixes #30

Feature/add missing cvc fields #30

---

src/main/java/com/bunq/sdk/model/generated/endpoint/DraftPayment.java
src/main/java/com/bunq/sdk/model/generated/object/DraftPaymentAnchorObject.java

Feature/fix draft payment object #29

---

build.gradle
src/main/java/com/bunq/sdk/context/ApiContext.java
src/main/java/com/bunq/sdk/json/GeolocationTypeAdapter.java

Removed guava as dependency. (bunq/sdk_java#41)

---

src/main/java/com/bunq/sdk/model/generated/endpoint/MasterCardAction.java
src/main/java/com/bunq/sdk/model/generated/endpoint/ShareInviteBankResponse.java

Added missing id field from mastercard action. (bunq/sdk_java#48)

---

README.md

Updated read me to point to tinker for examples. (bunq/sdk_java#81)

---

.travis.yml

Add travis ci bunq/sdk_java#80

---

src/main/java/com/bunq/sdk/context/ApiEnvironmentType.java
src/main/java/com/bunq/sdk/http/ApiClient.java

Changed sandbox url and pinned key. (bunq/sdk_java#89)

---

README.md

Update Sandbox API key procedure. (bunq/sdk_java#96)

---

build.gradle

Exclude examples and test files from build. (bunq/sdk_java#109)

---

src/main/java/com/bunq/sdk/model/core/OauthAccessToken.java

Use correct oauth url for sandbox and production

---

src/main/java/com/bunq/sdk/context/ApiEnvironmentType.java

Updated sandbox certificate pinning hash.

Updated sandbox certificate pinning hash.

---

build.gradle

Updated Java SDK dependencies

---

src/main/java/com/bunq/sdk/model/core/OauthAuthorizationUri.java
src/main/java/com/bunq/sdk/util/HttpUtil.java
src/test/java/com/bunq/sdk/model/core/OauthAuthorizationUriTest.java

- Closes bunq/sdk_java#126
All credit goes to @lazysasha for creating a [PR fixing this issue](https://github.com/bunq/sdk_java/pull/129).

Fixed OauthAuthorizationUri not being correctly created

---

src/main/java/com/bunq/sdk/context/SessionContext.java
src/main/java/com/bunq/sdk/context/UserContext.java

feature/sdk_java#134 Do not call getUser immediately after UserContext creation

---

build.gradle
src/main/java/com/bunq/sdk/context/ApiContext.java
src/main/java/com/bunq/sdk/context/BunqContext.java
src/main/java/com/bunq/sdk/context/SessionContext.java
src/main/java/com/bunq/sdk/context/UserContext.java
src/main/java/com/bunq/sdk/model/core/SessionServer.java
src/main/java/com/bunq/sdk/security/SecurityUtils.java
src/main/java/com/bunq/sdk/util/BunqUtil.java
src/test/java/com/bunq/sdk/BunqSdkTestBase.java
src/test/java/com/bunq/sdk/context/UserContextTest.java

feature/sdk_java#134 save/restore User in SessionContext from file

---

src/test/java/com/bunq/sdk/BunqSdkTestBase.java

feature/sdk_java#137 Deprecate sandbox-user.

---

src/main/java/com/bunq/sdk/context/ApiEnvironmentType.java
src/test/java/com/bunq/sdk/BunqSdkTestBase.java

Update certificate pin for sandbox
